# Generated by Django 5.1.4 on 2024-12-06 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('optimal_soil', models.CharField(max_length=100)),
                ('optimal_climate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_tracker_gardens', to=settings.AUTH_USER_MODEL)),
                ('plants', models.ManyToManyField(to='growth_tracker.plant')),
            ],
        ),
        migrations.CreateModel(
            name='PlantGrowthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('observation', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='plant_photos/')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growth_tracker.plant')),
            ],
        ),
    ]
