# Generated by Django 5.1.4 on 2024-12-07 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
        ('growth_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantgrowthlog',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.plant'),
        ),
        migrations.DeleteModel(
            name='Garden',
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
    ]
